contracts:
  - address: 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
    name: Switch
    events:
      - name: SwitchTurned(address,uint8)
        start: 0
      - name: UserChanged(address,address)
        start: 0
